repos:

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
          exclude: pgadmin.json
        - id: check-ast
        - id: check-json
        - id: check-toml
        - id: check-xml
        - id: check-yaml
        - id: debug-statements
        - id: check-builtin-literals
        - id: check-case-conflict
        - id: check-merge-conflict
        - id: check-docstring-first
        - id: check-added-large-files
          exclude: NazrulIslam.png
        - id: detect-private-key
        - id: detect-aws-credentials
          args: ['--allow-missing-credentials']
        - id: pretty-format-json
          args: ['--autofix']
          exclude: pgadmin.json
        - id: requirements-txt-fixer

    - repo: https://github.com/psf/black
      rev: 24.3.0
      hooks:
        - id: black

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.3.5
      hooks:
        - id: ruff
          args: [ --fix, --exit-non-zero-on-fix ]

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.15.1
      hooks:
        - id: pyupgrade
          args: [--py312-plus]
          exclude: hooks/

    - repo: https://github.com/asottile/add-trailing-comma
      rev: v3.1.0
      hooks:
        - id: add-trailing-comma
